export const triageCopyZh = {
  common: {
    save: "保存",
    cancel: "取消",
    edit: "编辑",
    select_book: "选择并预约",
    view_profile: "查看详情",
    doctor_placeholder: "医生",
    specialty_unavailable: "暂无专长信息",
    unnamed_patient: "未命名患者",
    no_summary_available: "暂无摘要。",
  },
  triage_card: {
    summary: "问诊摘要",
    possibility: "可能方向",
    recommended_department: "建议就诊专科",
    recommended_hospitals: "参考医院",
    next_step_title: "AI 已完成初步分诊，请选择一家医院继续就诊协助",
    next_step_description:
      "若信息无误，请点击下方医院进入下一步；如需补充信息，请开启新一轮问诊。",
    not_diagnosis: "这份结果只用于分诊和就医路径建议，不构成明确诊断。",
    browse_hospital: "查看服务说明并下单",
    reduced_confidence_title: "当前关键信息不足",
    reduced_confidence_description: (fields: string[]) =>
      `以下为初步分诊建议，建议补充${fields.join("、")}及相关伴随症状以提高准确性。`,
    critical_field_labels: {
      age: "年龄",
      gender: "性别",
    },
    platform_match: "已匹配站内医院",
    manual_coordination: "支持人工协调",
    no_hospitals: "暂未生成参考医院，请补充更多信息后重新开始分诊。",
    possibility_fallback:
      "当前信息更像某一类专科方向，建议线下面诊进一步评估。",
    department_fallback: "相关专科",
  },
  summary_form: {
    title: "AI 整理出的病情总结",
    description:
      "这是我根据对话整理出的结构化病情总结。请检查并修改不准确的地方，再带到下一步就诊。",
    age_gender: "年龄 / 性别",
    main_symptom_and_location: "核心症状与部位",
    duration_and_onset: "发病时间与急缓",
    trauma_or_surgery: "外伤与手术史",
    medical_history: "关键基础疾病",
    other_symptoms: "其他症状",
  },
  interruption: {
    eyebrow: "紧急提醒",
    title: "检测到高风险症状，AI 分诊已停止",
    description:
      "您提供的信息提示可能存在紧急医疗风险。请不要继续在聊天中等待，建议立即前往线下就医。",
    next_steps_title: "建议您现在就做",
    next_steps: [
      "如果症状突然出现、明显加重，或已影响说话、呼吸、意识，请立即联系当地急救服务。",
      "如暂不需要呼叫急救，也请尽快前往最近的急诊或紧急门诊，由线下医生立即评估。",
      "如条件允许，请携带目前用药、过敏史、既往病史以及近期检查结果一同就诊。",
    ],
    primary_cta: "去看医院库",
    secondary_cta: "返回首页",
    footer:
      "此安全中断用于减少潜在急症的等待时间，不建议继续依赖当前聊天获得处置意见。",
  },
  sidebar: {
    new_session: "新会话",
    today: "今天",
    previous_7_days: "过去 7 天",
    older: "更早",
    load_failed: "会话记录加载失败，请刷新后重试。",
    empty: "暂无历史会话。",
    no_messages_in_session: "当前会话暂无消息。",
    read_only_placeholder: "这是历史会话（只读）...",
  },
  status: {
    typing: "AI 正在输入...",
    reviewing: "AI 正在整理分诊信息...",
    thinking: "AI 正在思考...",
    quota_login_required: "游客试用额度已尽，请登录后继续问诊。",
    message_limit_reached:
      "本次会诊已达到消息上限，请尽快查看建议专科和参考医院。",
    message_limit_action: "选择医院继续",
  },
  patientLabel: "患者",
  triage: {
    disclaimer: "AI 可能会产生错误信息。在做出医疗决定前，请务必咨询专业医生。",
    post_complete_input_title: "当前主要操作是选择医院继续",
    post_complete_input_description:
      "分诊结果已经生成，建议优先点击上方医院进入下一步；如需补充症状，请开启新一轮问诊。",
  },
  doctor_detail: {
    about: "医生信息",
    biography: "个人简介",
    confirm_book: "确认选择并预约",
    years_experience: (years: number) => `从业 ${years} 年`,
  },
  fast_intake: {
    title: "快捷表单（可选）",
    description:
      "如果不方便聊天，可以改用简表；默认仍然是 AI 在 2-3 轮内主动引导分诊。",
    age: "年龄",
    gender: "性别",
    gender_placeholder: "请选择性别",
    gender_male: "男",
    gender_female: "女",
    gender_other: "其他",
    gender_unknown: "不便说明",
    main_symptom: "核心症状与部位",
    main_symptom_placeholder: "例如：右下腹痛 / 胸闷 / 腿部皮肤破损",
    duration_onset: "发病时间与急缓",
    duration_onset_placeholder:
      "例如：今天早上突然出现 / 3 天来逐渐加重 / 2 个月反复发作",
    trauma_surgery: "外伤与手术史",
    trauma_surgery_placeholder: "例如：无 / 昨天摔伤 / 近期做过手术",
    chronic_conditions: "关键基础疾病",
    chronic_conditions_placeholder:
      "例如：无 / 糖尿病 / 高血压 / 心脏病 / 肿瘤",
    submit: "提交快捷表单",
    skip: "继续聊天",
    required: "请至少填写一项关键信息后再提交表单。",
  },
  title: "AI 预诊分诊",
  subtitle:
    "请先用自己的话描述不适，AI 会在前 2-3 轮内主动引导并完成专科和医院推荐。",
  placeholder: "请在这里描述您的症状...",
  typing: "AI 正在整理分诊信息...",
  requestError: "分诊服务暂时不可用，请稍后重试。",
  fallbackReply: "抱歉，当前分诊服务繁忙。请稍后再试。",
  completed: "分诊已完成，建议专科和参考医院已生成。",
  summaryTitle: "病情摘要",
  summaryDesc: "可直接用于下一步预约/建会话的结构化摘要。",
  summaryEmpty: "尚未完成分诊，摘要会在完成后显示。",
  doctorTitle: "参考医院",
  doctorDesc: "根据建议专科给出前 5 家参考医院",
  searching: "正在整理推荐结果...",
  doctorQueryError: "医院推荐加载失败，请重试或刷新当前会话。",
  noDoctor: "暂未生成参考医院，请补充更具体症状。",
  noBio: "暂无医生简介",
  viewProfile: "查看详情",
  chooseBook: "选择并预约",
  whatsapp: "WhatsApp 预约",
  startNew: "开始新会话",
  disclaimerTitle: "医疗免责声明",
  disclaimerDesc: "AI 建议仅用于分诊与医院/专科路径推荐，不构成医疗诊断。",
  disclaimerLine1: "请勿在对话中发送高敏感身份信息（证件号/护照号等）。",
  disclaimerLine2:
    "如出现胸痛、呼吸困难、中风征象、大出血等急症，请立即联系当地急救服务。",
  cancel: "取消",
  understand: "我已知悉",
  rating: "评分",
  doctorFallback: "参考医院",
  bookingTitle: "创建预约",
  bookingDesc: "填写邮箱与预约时间，系统将发送安全魔法链接。",
  bookingEmail: "邮箱",
  bookingTime: "预约时间",
  bookingType: "预约类型",
  bookingTypeOnline: "在线图文",
  bookingTypeVideo: "视频问诊",
  bookingTypeInPerson: "线下面诊",
  bookingCancel: "取消",
  bookingConfirm: "创建预约",
  bookingCreating: "创建中...",
  bookingInvalid: "请完整填写邮箱和预约时间。",
  bookingSuccess: "预约创建成功，正在跳转支付页。",
  bookingFailed: "预约创建失败，请稍后重试。",
  bookingEmailPlaceholder: "you@example.com",
  bookingOtpLabel: "邮箱验证码",
  bookingOtpPlaceholder: "请输入 6 位验证码",
  bookingSendOtp: "发送验证码",
  bookingSendingOtp: "发送中...",
  bookingResendOtp: "重新发送",
  bookingOtpSent: "验证码已发送，请查看邮箱。",
  bookingOtpCooldown: "{seconds}s 后可重试",
  bookingOtpRequired: "请输入 6 位验证码。",
  bookingVerifyingIdentity: "正在验证身份...",
  bookingIdentityVerified: "邮箱验证成功。",
  bookingIdentityVerifyFailed: "邮箱验证失败，请重试。",
  bookingDeviceIdMissing: "无法获取设备标识，请刷新页面后重试。",
  initialAssistantMessage:
    "如果方便，请先告诉我年龄和性别。然后我们按 4 个问题来，这样我能更快帮您判断专科和医院：1. 现在最主要的不适是什么，具体在哪个部位？2. 这个症状出现多久了，是突然发生还是逐渐加重/反复发作？3. 这次不适和外伤或近期手术有没有关系？4. 有没有需要特别注意的基础疾病，比如糖尿病、高血压或心脏病、免疫系统疾病或肿瘤？没有可直接写“无”。",
  reasonFallback: "基于分诊信息推荐",
  bookingSummaryFallback: "已在 AI 对话中提供症状描述",
  bookingSymptomsFallback: "已在分诊中描述",
  bookingDurationFallback: "未明确",
} as const;
