export type DashboardLang = "en" | "zh";

export const DASHBOARD_COPY = {
  en: {
    appLayoutTitle: "User Center",
    pageTitle: "Dashboard",
    welcomeBack: "Welcome back, {{name}}",
    fallbackUserName: "MediBridge user",
    tabAccount: "Account",
    tabConsultations: "Consultations",
    tabAppointments: "My Appointments",
    accountBilling: "Account & Billing",
    unlimited: "Unlimited",
    loadingAccount: "Loading account information...",
    remainingToday: "Remaining consultations today: {{count}}",
    totalSessions: "Total AI sessions: {{count}}",
    upgradePro: "Upgrade to Pro",
    aiConsultations: "AI Consultations",
    loadingConsultations: "Loading consultation history...",
    sessionLabel: "Session #{{id}}",
    createdAt: "Created at: {{time}}",
    noConsultations: "No AI consultation history yet.",
    guardTitle: "Please sign in to view your dashboard",
    guardDesc: "After signing in, you can view account status, consultation history, and appointments.",
    guardAction: "Sign in / Register",
  },
  zh: {
    appLayoutTitle: "个人中心",
    pageTitle: "个人中心",
    welcomeBack: "欢迎回来，{{name}}",
    fallbackUserName: "MediBridge 用户",
    tabAccount: "账户状态",
    tabConsultations: "我的问诊记录",
    tabAppointments: "我的行程",
    accountBilling: "账户与计费",
    unlimited: "无限制",
    loadingAccount: "正在加载账户信息...",
    remainingToday: "今日剩余可用问诊次数：{{count}}",
    totalSessions: "累计 AI 会话数：{{count}}",
    upgradePro: "升级 Pro",
    aiConsultations: "AI 问诊记录",
    loadingConsultations: "正在加载问诊记录...",
    sessionLabel: "会话 #{{id}}",
    createdAt: "创建时间：{{time}}",
    noConsultations: "暂无 AI 问诊记录。",
    guardTitle: "请先登录以查看您的个人资料",
    guardDesc: "登录后可查看账户状态、问诊记录与行程安排。",
    guardAction: "登录/注册",
  },
} as const;

export const DASHBOARD_APPOINTMENT_COPY = {
  en: {
    title: "My Appointments",
    sectionUpcoming: "Upcoming",
    sectionCompleted: "Completed",
    sectionPast: "Past",
    tableDoctor: "Doctor",
    tableTime: "Time",
    tableType: "Type",
    tableStatus: "Status",
    tableActions: "Actions",
    doctorTimeChina: "Doctor time (China)",
    emptySection: "No appointments in this section.",
    loadingAppointments: "Loading appointments...",
    payNow: "Pay Now",
    enterVisitRoom: "Enter Visit Room",
    viewRecord: "View Record",
    view: "View",
    resendLink: "Resend Link",
    hintPendingPayment: "Complete payment to unlock visit room.",
    hintPaid: "Paid, waiting for doctor to start.",
    hintActive: "Active, chat available.",
    hintEnded: "Visit completed, read-only.",
    hintInactive: "This appointment is not active.",
    accessSentEmail: "Access link sent to your email.",
    accessSent: "Access link sent.",
    actionFailed: "Action failed.",
    resendFailed: "Failed to resend link.",
    typeOnline: "Online chat",
    typeVideo: "Video call",
    typeInPerson: "In person",
    statusDraft: "Draft",
    statusPendingPayment: "Pending payment",
    statusPaid: "Paid",
    statusActive: "Active",
    statusEnded: "Ended",
    statusExpired: "Expired",
    statusRefunded: "Refunded",
    statusCanceled: "Canceled",
    doctorFallback: "Doctor #{{id}}",
  },
  zh: {
    title: "我的行程",
    sectionUpcoming: "即将开始",
    sectionCompleted: "已完成",
    sectionPast: "历史记录",
    tableDoctor: "医生",
    tableTime: "时间",
    tableType: "类型",
    tableStatus: "状态",
    tableActions: "操作",
    doctorTimeChina: "医生时间（中国）",
    emptySection: "该分组暂无预约。",
    loadingAppointments: "正在加载预约...",
    payNow: "立即支付",
    enterVisitRoom: "进入会诊室",
    viewRecord: "查看记录",
    view: "查看",
    resendLink: "重发链接",
    hintPendingPayment: "请先完成支付后进入会诊室。",
    hintPaid: "已支付，等待医生开始。",
    hintActive: "会诊进行中，可发送消息。",
    hintEnded: "会诊已完成，仅可只读查看。",
    hintInactive: "当前预约不可进入会诊。",
    accessSentEmail: "访问链接已发送到你的邮箱。",
    accessSent: "访问链接已发送。",
    actionFailed: "操作失败。",
    resendFailed: "重发链接失败。",
    typeOnline: "图文会诊",
    typeVideo: "视频会诊",
    typeInPerson: "线下面诊",
    statusDraft: "草稿",
    statusPendingPayment: "待支付",
    statusPaid: "已支付",
    statusActive: "进行中",
    statusEnded: "已结束",
    statusExpired: "已过期",
    statusRefunded: "已退款",
    statusCanceled: "已取消",
    doctorFallback: "医生 #{{id}}",
  },
} as const;

export function getDashboardCopy(lang: DashboardLang) {
  return DASHBOARD_COPY[lang];
}

export function getDashboardAppointmentCopy(lang: DashboardLang) {
  return DASHBOARD_APPOINTMENT_COPY[lang];
}

