export type DashboardLang = "en" | "zh";

export const DASHBOARD_COPY = {
  en: {
    appLayoutTitle: "User Center",
    pageTitle: "Dashboard",
    welcomeBack: "Welcome back, {{name}}",
    fallbackUserName: "MediBridge user",
    tabAccount: "Account",
    tabConsultations: "Consultations",
    tabAppointments: "My Appointments",
    sidebarAccountOverview: "Account Overview",
    sidebarAiConsultations: "AI Consultations",
    sidebarMyAppointments: "My Appointments",
    accountBilling: "Account & Billing",
    unlimited: "Unlimited",
    loadingAccount: "Loading account information...",
    remainingToday: "Remaining consultations today: {{count}}",
    totalSessions: "Total AI sessions: {{count}}",
    upgradePro: "Upgrade to Pro",
    aiConsultations: "AI Consultations",
    loadingConsultations: "Loading consultation history...",
    sessionLabel: "Session #{{id}}",
    triageArchiveTitle: "Triage Archive",
    triageArchiveDesc:
      "Review the latest AI triage outcome, then continue chatting or move on to booking.",
    createdAt: "Created at: {{time}}",
    updatedAt: "Last updated: {{time}}",
    completedSummaryFallback:
      "Triage summary is ready. Open the record to review the result and next steps.",
    activeSummaryFallback:
      "This triage is still in progress. Continue the conversation to complete the summary.",
    continueTriage: "Continue Triage",
    reviewRecord: "Review Record",
    statusActive: "In progress",
    statusCompleted: "Summary ready",
    noConsultations: "No AI consultation history yet.",
    guardTitle: "Please sign in to view your dashboard",
    guardDesc: "After signing in, you can view account status, consultation history, and appointments.",
    guardAction: "Sign in / Register",
  },
  zh: {
    appLayoutTitle: "个人中心",
    pageTitle: "个人中心",
    welcomeBack: "欢迎回来，{{name}}",
    fallbackUserName: "MediBridge 用户",
    tabAccount: "账户状态",
    tabConsultations: "我的问诊记录",
    tabAppointments: "我的行程",
    sidebarAccountOverview: "账户概览",
    sidebarAiConsultations: "AI 问诊记录",
    sidebarMyAppointments: "我的预约",
    accountBilling: "账户与计费",
    unlimited: "无限制",
    loadingAccount: "正在加载账户信息...",
    remainingToday: "今日剩余可用问诊次数：{{count}}",
    totalSessions: "累计 AI 会话数：{{count}}",
    upgradePro: "升级 Pro",
    aiConsultations: "AI 问诊记录",
    loadingConsultations: "正在加载问诊记录...",
    sessionLabel: "会话 #{{id}}",
    triageArchiveTitle: "分诊档案",
    triageArchiveDesc: "这里保留每次 AI 分诊的结果摘要，方便继续问诊或进入下一步预约。",
    createdAt: "创建时间：{{time}}",
    updatedAt: "最近更新：{{time}}",
    completedSummaryFallback: "分诊摘要已生成，可打开记录查看结果和下一步建议。",
    activeSummaryFallback: "当前分诊尚未完成，可继续补充症状让 AI 完成总结。",
    continueTriage: "继续问诊",
    reviewRecord: "查看记录",
    statusActive: "进行中",
    statusCompleted: "摘要已生成",
    noConsultations: "暂无 AI 问诊记录。",
    guardTitle: "请先登录以查看您的个人资料",
    guardDesc: "登录后可查看账户状态、问诊记录与行程安排。",
    guardAction: "登录/注册",
  },
} as const;

export const DASHBOARD_APPOINTMENT_COPY = {
  en: {
    title: "My Appointments",
    tabUpcoming: "Upcoming",
    tabPastVisits: "Past Visits",
    sectionUpcoming: "Upcoming",
    sectionCompleted: "Completed",
    sectionPast: "Past",
    tableDoctor: "Doctor",
    tableTime: "Time",
    tableType: "Type",
    tableStatus: "Status",
    tableActions: "Actions",
    localTimeLabel: "Local time",
    chinaTimeLabel: "China time (China) 🇨🇳",
    doctorTimeChina: "Doctor time (China)",
    emptySection: "No appointments in this section.",
    loadingAppointments: "Loading appointments...",
    payNow: "Pay Now",
    enterVisitRoom: "Enter Visit Room",
    viewRecord: "View Record",
    view: "View",
    viewMedicalSummary: "View Medical Summary",
    viewChatHistory: "View Chat History",
    resendLink: "Resend Link",
    medicalSummaryModalTitle: "Medical Summary",
    medicalSummaryModalSubtitle: "Official doctor-issued record for this consultation.",
    medicalSummaryClose: "Close medical summary",
    medicalSummaryDoctorLabel: "Attending doctor",
    medicalSummaryTimeLabel: "Consultation time",
    medicalSummaryIssuedAtLabel: "Issued at",
    medicalSummaryLoading: "Loading medical summary...",
    medicalSummaryEmpty: "No signed medical summary is available for this visit yet.",
    medicalSummaryLoadFailed: "Failed to load medical summary.",
    medicalSummaryDisclaimer:
      "System generated archival view. This summary is for clinical reference only and does not replace emergency care.",
    hintPendingPayment: "Complete payment to unlock visit room.",
    hintPaid: "Paid, waiting for doctor to start.",
    hintNotStarted: "Not started yet. Please enter at the scheduled time.",
    hintActive: "Active, chat available.",
    hintEnded: "Visit completed, read-only.",
    hintInactive: "This appointment is not active.",
    accessSentEmail: "Access link sent to your email.",
    accessSent: "Access link sent.",
    actionFailed: "Action failed.",
    resendFailed: "Failed to resend link.",
    typeOnline: "Online chat",
    typeVideo: "Video call",
    typeInPerson: "In person",
    statusDraft: "Draft",
    statusPendingPayment: "Pending payment",
    statusNotStarted: "Not Started",
    statusPaid: "Paid",
    statusActive: "Active",
    statusEnded: "Ended",
    statusCompleted: "Completed",
    statusExpired: "Expired",
    statusRefunded: "Refunded",
    statusCanceled: "Canceled",
    doctorFallback: "Doctor #{{id}}",
  },
  zh: {
    title: "我的行程",
    tabUpcoming: "即将开始",
    tabPastVisits: "历史就诊",
    sectionUpcoming: "即将开始",
    sectionCompleted: "已完成",
    sectionPast: "历史记录",
    tableDoctor: "医生",
    tableTime: "时间",
    tableType: "类型",
    tableStatus: "状态",
    tableActions: "操作",
    localTimeLabel: "本地时间",
    chinaTimeLabel: "中国时间（中国）🇨🇳",
    doctorTimeChina: "医生时间（中国）",
    emptySection: "该分组暂无预约。",
    loadingAppointments: "正在加载预约...",
    payNow: "立即支付",
    enterVisitRoom: "进入会诊室",
    viewRecord: "查看记录",
    view: "查看",
    viewMedicalSummary: "查看病历",
    viewChatHistory: "查看聊天记录",
    resendLink: "重发链接",
    medicalSummaryModalTitle: "病历摘要",
    medicalSummaryModalSubtitle: "医生签发后的正式就诊记录。",
    medicalSummaryClose: "关闭病历摘要",
    medicalSummaryDoctorLabel: "接诊医生",
    medicalSummaryTimeLabel: "问诊时间",
    medicalSummaryIssuedAtLabel: "签发时间",
    medicalSummaryLoading: "正在加载病历摘要...",
    medicalSummaryEmpty: "当前就诊尚未签发最终病历。",
    medicalSummaryLoadFailed: "加载病历摘要失败。",
    medicalSummaryDisclaimer:
      "本报告由系统归档生成，仅用于就诊留存与复诊参考，不作为紧急医疗处置依据。",
    hintPendingPayment: "请先完成支付后进入会诊室。",
    hintPaid: "已支付，等待医生开始。",
    hintNotStarted: "未到预约时间，请在预约开始后进入会诊室。",
    hintActive: "会诊进行中，可发送消息。",
    hintEnded: "会诊已完成，仅可只读查看。",
    hintInactive: "当前预约不可进入会诊。",
    accessSentEmail: "访问链接已发送到你的邮箱。",
    accessSent: "访问链接已发送。",
    actionFailed: "操作失败。",
    resendFailed: "重发链接失败。",
    typeOnline: "图文会诊",
    typeVideo: "视频会诊",
    typeInPerson: "线下面诊",
    statusDraft: "草稿",
    statusPendingPayment: "待支付",
    statusNotStarted: "未开始",
    statusPaid: "已支付",
    statusActive: "进行中",
    statusEnded: "已结束",
    statusCompleted: "已完成",
    statusExpired: "已过期",
    statusRefunded: "已退款",
    statusCanceled: "已取消",
    doctorFallback: "医生 #{{id}}",
  },
} as const;

export function getDashboardCopy(lang: DashboardLang) {
  return DASHBOARD_COPY[lang];
}

export function getDashboardAppointmentCopy(lang: DashboardLang) {
  return DASHBOARD_APPOINTMENT_COPY[lang];
}
