export type ReferralLang = "en" | "zh";

const referralCopyByLang = {
  en: {
    navigation: {
      backToTriage: "Back to Triage",
      backToSelection: "Back to Contact Selection",
      backToConfirmation: "Back to Confirmation",
      backToOrders: "Back to My Orders",
      backToDashboard: "Back to Dashboard",
      backToOrder: "Back to Order",
    },
    statusLabels: {
      pending_payment: "Pending payment",
      paid_pending_assignment: "Paid, waiting for assignment",
      assigned: "Assigned",
      contacting: "Contacting channel",
      booking_in_progress: "Booking in progress",
      time_coordination: "Coordinating consultation time",
      scheduled: "Consultation scheduled",
      completed: "Completed",
      refund_pending_review: "Refund under review",
      refund_processing: "Refund processing",
      refunded: "Refunded",
      cancelled: "Cancelled",
    },
    refundStatusLabels: {
      pending_review: "Pending review",
      approved: "Approved",
      processing: "Processing",
      refunded: "Refunded",
      rejected: "Rejected",
    },
    operationLabels: {
      patient_notification: "Progress update shared with you",
      consultation_time_confirmed: "Consultation time confirmed",
      consultation_time_updated: "Consultation time updated",
      refund_requested: "Refund requested",
      refund_completed: "Refund completed",
    },
    common: {
      loading: "Loading referral details...",
      unknown: "Unknown",
      notAvailable: "Not available",
      contactPending: "MediBridge Coordination Team",
      refresh: "Refresh",
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      active: "Active",
      inactive: "Inactive",
      none: "None",
    },
    selection: {
      eyebrow: "Referral MVP",
      title: "Select a MediBridge Platform Coordinator",
      description:
        "Choose the MediBridge platform coordinator who will help contact the selected hospital and arrange the next steps.",
      recommendedDepartment: "Recommended department",
      noContacts:
        "No individual coordinator is currently available for this hospital.",
      teamName: "MediBridge Coordination Team",
      teamDescription:
        "The MediBridge platform team will assign an appropriate coordinator after payment. This team is not an official hospital department.",
      coordinatorRole: "MediBridge platform coordinator",
      contactLanguages: "Languages",
      contactSpecialties: "Tags",
      responseTime: "Avg. response",
      successRate: "Success rate",
      chooseContact: "Choose this coordinator",
      chooseTeam: "Choose the coordination team",
      triageSummary: "Triage summary",
      loadFailed: "Failed to load referral contact options.",
    },
    confirmation: {
      title: "Confirm Referral Service",
      description:
        "Review the service scope before creating the referral order.",
      hospital: "Selected hospital",
      contact: "MediBridge platform coordinator",
      fulfillmentDescription:
        "After payment, the selected MediBridge platform coordinator will contact the hospital and continue the registration and scheduling process.",
      serviceDescription:
        "The ¥199 fee covers MediBridge coordination only: contacting the selected hospital, assisting with registration, and coordinating an online consultation time. Hospital registration, physician consultation, and other third-party fees are not included.",
      priceLabel: "Service fee",
      refundPolicyTitle: "Refund policy",
      refundPolicy:
        "The ¥199 service fee will be fully refunded to the original payment method if contact or registration clearly fails, or if no schedulable response is received within two business days after payment.",
      disclaimerTitle: "Disclaimer",
      disclaimer:
        "MediBridge provides coordination support and does not guarantee registration, diagnosis, treatment, or medical outcomes. The selected coordinator is a MediBridge platform representative, not hospital staff.",
      manualHandlingNotice:
        "After your order is placed, we will manually coordinate with the hospital or doctor based on the triage recommendation.",
      agreementLabel:
        "I understand the service scope, refund rule, and disclaimer, and I agree to proceed.",
      continueToPayment: "Continue to Payment",
      agreementRequired: "Please accept the agreement before continuing.",
      invalidContact:
        "The selected coordinator is no longer available for this hospital. Please return and choose again.",
      loadFailed: "Failed to load referral confirmation details.",
    },
    payment: {
      title: "Pay Service Fee",
      description:
        "Complete payment to create a paid referral order for internal broker handling.",
      payNow: "Pay now",
      processing: "Processing...",
      alreadyPaid: "This referral order is already paid.",
      paymentFailed: "Payment could not be completed. Please try again.",
      paymentWaiting: "Preparing payment session...",
      missingOrder: "Referral order is missing or unavailable.",
      selectedHospital: "Hospital",
      selectedContact: "Internal handling",
      currentStatus: "Current status",
      serviceFee: "Service fee",
      payHelp:
        "After payment, the order will move into internal handling and assignment.",
      successTitle: "Payment confirmed",
      successDescription:
        "Your referral order has been created and sent for internal assignment.",
      successMissingSession: "Payment session is missing from the return URL.",
      cancelTitle: "Payment cancelled",
      cancelDescription:
        "The referral order is still waiting for payment. You can return and continue later.",
      viewOrder: "View referral order",
      retryPayment: "Retry payment",
      continuePayment: "Continue payment",
      paymentReturnedError: "Unable to confirm the payment result right now.",
      mockTitle: "Demo payment screen",
      mockDescription:
        "Referral mock checkout is enabled for local demos. Use the actions below to simulate the payment result.",
      mockOrderLabel: "Referral order",
      mockSuccess: "Simulate payment success",
      mockCancel: "Simulate payment cancel",
      mockDisabled:
        "Referral mock checkout is unavailable. Turn on VITE_REFERRAL_MOCK_CHECKOUT=1 in development to use this page.",
    },
    orderDetail: {
      title: "Referral Order",
      latestUpdate: "Latest update",
      latestUpdateTime: "Updated",
      latestUpdateFallback:
        "Your referral request is in progress. We will keep this page updated.",
      pendingPaymentNotice:
        "Please complete payment first. We will start manual coordination after payment is confirmed.",
      consultationConfirmedNotice:
        "Your consultation time has been confirmed. Please attend at the scheduled time shown below. We will notify you if it changes.",
      consultationTime: "Consultation time",
      fulfillmentDeadline: "Coordination response deadline",
      consultationProvider: "Doctor or service provider",
      consultationPlatform: "Consultation platform",
      consultationTimeZone: "Time zone",
      consultationJoinLink: "Join consultation",
      consultationInstructions: "Joining instructions",
      refundStatus: "Refund status",
      timeline: "Status timeline",
      noTimeline: "No status updates yet.",
      assignedAgent: "Assigned agent",
      serviceFee: "Service fee",
      triageSummary: "Case summary snapshot",
      recommendationReason: "Recommendation reason",
      manualFulfillmentNotice:
        "This order is being handled through manual coordination. Our team is continuing to reach out to the hospital or doctor and advance the next steps.",
      selectedHospital: "Hospital",
      selectedContact: "Internal handling",
      agreementVersion: "Agreement version",
      orderId: "Order ID",
      loadFailed: "Failed to load referral order details.",
      systemProgress: {
        paymentReceived:
          "Payment received. Your referral request is now waiting for internal assignment.",
        consultationTimeConfirmed: "Consultation time confirmed.",
        refundReviewInProgress:
          "A refund review is in progress for your referral order.",
        refundReviewInitiated: "Refund review initiated.",
        refundCompleted: "Refund completed.",
      },
    },
    dashboard: {
      title: "Referral Orders",
      empty: "No referral orders yet.",
      viewOrder: "Open order",
      consultationTime: "Consultation time",
      latestStatus: "Latest status",
    },
    admin: {
      title: "Referral Operations",
      description:
        "Manage paid referral orders, internal handling progress, and refund outcomes.",
      workspaceTabs: {
        workbench: "Order tracking workspace",
        catalog: "Hospitals & catalog (Admin)",
        catalogPermission: "Admin only",
      },
      detailTabs: {
        operations: "Progress & actions",
        patient: "Patient triage info",
        refund: "Refund management",
        timeline: "Timeline & logs",
      },
      filtersTitle: "Order filters",
      statusFilter: "Status",
      statusAll: "All statuses",
      assignedToMe: "Assigned to me",
      sortDirection: "Sort direction",
      sortNewest: "Newest first",
      sortOldest: "Oldest first",
      refresh: "Refresh orders",
      orderListTitle: "Referral order list",
      orderDetailTitle: "Referral order detail",
      noOrders: "No referral orders found.",
      urgencyMinutes: "Open for {{minutes}} min",
      unassigned: "Unassigned",
      contactPending: "Contact pending assignment",
      manualFulfillmentBadge: "Manual outreach",
      manualFulfillmentDetail:
        "This order was created from a triage-ranked hospital and still needs manual outreach or local mapping follow-up.",
      noLocalHospitalMapping:
        "This order does not have a local hospital mapping yet. Continue manual outreach, or add the hospital to the local catalog later if needed.",
      recommendationReason: "Recommendation reason",
      patient: "Patient",
      triageSummary: "Patient summary",
      timeline: "Timeline",
      operations: "Operations",
      notificationFailures: "Notification delivery failures",
      noNotificationFailures: "No terminal notification failures.",
      claimOrder: "Claim order",
      assignOrder: "Assign order",
      assignPlaceholder: "Select assignee",
      assignContactTitle: "Assign contact",
      assignContact: "Save contact",
      assignContactPlaceholder: "Select hospital contact",
      noContactsForHospital:
        "No active contacts are configured for this hospital yet. Keep the order in manual handling for now.",
      updateStatus: "Update status",
      reason: "Reason",
      note: "Note",
      addNote: "Add note",
      patientProgressTitle: "Patient-visible progress update",
      patientProgressPlaceholder:
        "Share a progress update that will appear on the patient's referral order page.",
      publishPatientProgress: "Publish progress update",
      contactAttemptTitle: "Contact attempt",
      bookingResultTitle: "Booking progress",
      consultationTimeTitle: "Consultation time",
      beginTimeCoordination: "Start time coordination",
      refundTitle: "Refund handling",
      actionOutcome: "Outcome",
      actionSuccess: "Saved",
      consultationTimeInput: "Confirmed consultation time",
      consultationTimeZone: "IANA time zone, e.g. Asia/Shanghai",
      consultationProviderName: "Doctor or service provider",
      consultationPlatform: "Consultation platform",
      consultationJoinUrl: "HTTPS joining link",
      consultationInstructions: "Patient joining instructions",
      consultationTimeNote: "Scheduling note",
      initiateRefund: "Initiate refund",
      approveRefund: "Approve refund",
      rejectRefund: "Reject refund",
      refundReasonCode: "Refund reason",
      refundReasonDetail: "Refund detail",
      refundReviewNote: "Review note",
      noSelection: "Select an order to review details.",
      loadFailed: "Failed to load referral admin data.",
      paymentStatus: "Payment status",
      listSummary:
        "Focus the queue on the left and handle the active order on the right.",
      detailSummary:
        "Keep operational controls and deep logs separated so long cases stay manageable.",
      prevPage: "Previous",
      nextPage: "Next",
      refundReasonCodes: {
        contact_failed: "Contact failed",
        booking_failed: "Booking failed",
        sla_expired: "Two-business-day response deadline expired",
        patient_requested: "Patient requested",
        internal_exception: "Internal exception",
      },
      contactOutcomes: {
        connected: "Connected",
        no_response: "No response",
        failed: "Failed",
      },
      bookingOutcomes: {
        progressing: "Progressing",
        failed: "Failed",
        scheduled: "Scheduled",
      },
      catalog: {
        title: "Hospital & Contact Catalog",
        description:
          "Maintain the hospitals and referral contacts available to the MVP flow.",
        hospitals: "Hospitals",
        contacts: "Contacts",
        department: "Department",
        createHospital: "Create hospital",
        editHospital: "Edit hospital",
        createContact: "Create contact",
        editContact: "Edit contact",
        nameZh: "Name (ZH)",
        nameEn: "Name (EN)",
        cityZh: "City (ZH)",
        cityEn: "City (EN)",
        contactName: "Contact name",
        roleType: "Role / title",
        languages: "Languages",
        specialtyTags: "Specialty tags",
        avgResponseTime: "Avg. response time (min)",
        successRate: "Success rate (%)",
        internalNotes: "Internal notes",
        selectedHospital: "Hospital",
        activeState: "Active state",
        saveHospital: "Save hospital",
        saveContact: "Save contact",
        emptyHospitals: "No hospitals available.",
        emptyContacts: "No referral contacts available.",
      },
    },
  },
  zh: {
    navigation: {
      backToTriage: "返回问诊结果",
      backToSelection: "返回联系人选择",
      backToConfirmation: "返回确认页",
      backToOrders: "返回我的订单",
      backToDashboard: "返回个人中心",
      backToOrder: "返回订单",
    },
    statusLabels: {
      pending_payment: "待支付",
      paid_pending_assignment: "已支付，待分配",
      assigned: "已分配",
      contacting: "联系渠道中",
      booking_in_progress: "挂号处理中",
      time_coordination: "协调问诊时间中",
      scheduled: "问诊时间已确认",
      completed: "已完成",
      refund_pending_review: "退款审核中",
      refund_processing: "退款处理中",
      refunded: "已退款",
      cancelled: "已取消",
    },
    refundStatusLabels: {
      pending_review: "待审核",
      approved: "已批准",
      processing: "处理中",
      refunded: "已退款",
      rejected: "已拒绝",
    },
    operationLabels: {
      patient_notification: "系统已同步最新进展",
      consultation_time_confirmed: "问诊时间已确认",
      consultation_time_updated: "问诊时间已更新",
      refund_requested: "已发起退款",
      refund_completed: "退款已完成",
    },
    common: {
      loading: "正在加载转诊信息...",
      unknown: "未知",
      notAvailable: "暂无",
      contactPending: "MediBridge 协调团队",
      refresh: "刷新",
      save: "保存",
      cancel: "取消",
      edit: "编辑",
      active: "启用",
      inactive: "停用",
      none: "无",
    },
    selection: {
      eyebrow: "转诊服务 MVP",
      title: "选择 MediBridge 平台协调专员",
      description:
        "请选择协助联系所选医院、推进挂号并协调后续时间的 MediBridge 平台协调专员。",
      recommendedDepartment: "推荐科室",
      noContacts: "当前暂无负责该医院的可选个人协调专员。",
      teamName: "MediBridge 协调团队",
      teamDescription:
        "支付后将由 MediBridge 平台团队分配合适的协调专员；该团队并非医院官方科室或工作人员。",
      coordinatorRole: "MediBridge 平台协调专员",
      contactLanguages: "支持语言",
      contactSpecialties: "标签",
      responseTime: "平均响应",
      successRate: "成功率",
      chooseContact: "选择该协调专员",
      chooseTeam: "选择平台协调团队",
      triageSummary: "分诊摘要",
      loadFailed: "加载转诊联系人失败。",
    },
    confirmation: {
      title: "确认转诊服务",
      description: "在创建转诊订单前，请先确认服务范围与规则。",
      hospital: "已选医院",
      contact: "MediBridge 平台协调专员",
      fulfillmentDescription:
        "支付后将由所选 MediBridge 平台协调专员协助联系医院，并继续推进挂号与时间协调。",
      serviceDescription:
        "¥199 为 MediBridge 协调服务费，仅包含联系所选医院、协助挂号及协调线上面诊时间；不包含医院挂号费、医生诊疗费及其他第三方费用。",
      priceLabel: "服务费",
      refundPolicyTitle: "退款规则",
      refundPolicy:
        "如明确联系失败、明确挂号失败，或付款后两个工作日内仍未取得可安排反馈，¥199 服务费将全额原路退回。",
      disclaimerTitle: "免责声明",
      disclaimer:
        "MediBridge 仅提供协调支持，不保证挂号结果、诊疗效果或其他医疗结果。平台协调专员并非医院官方人员。",
      manualHandlingNotice:
        "下单后，平台会依据分诊建议人工协调医院或医生，继续推进就诊协助。",
      agreementLabel: "我已理解服务范围、退款规则与免责声明，并同意继续。",
      continueToPayment: "继续支付",
      agreementRequired: "请先勾选同意后再继续。",
      invalidContact:
        "所选协调专员已失效或不再负责该医院，请返回后重新选择。",
      loadFailed: "加载转诊确认信息失败。",
    },
    payment: {
      title: "支付服务费",
      description: "完成支付后，系统会创建已支付的转诊订单并进入内部处理。",
      payNow: "立即支付",
      processing: "处理中...",
      alreadyPaid: "该转诊订单已完成支付。",
      paymentFailed: "支付未成功，请稍后重试。",
      paymentWaiting: "正在准备支付会话...",
      missingOrder: "转诊订单不存在或暂不可用。",
      selectedHospital: "医院",
      selectedContact: "内部处理",
      currentStatus: "当前状态",
      serviceFee: "服务费",
      payHelp: "支付完成后，订单会进入内部处理与分配流程。",
      successTitle: "支付已确认",
      successDescription: "你的转诊订单已创建，并已发送至内部处理队列。",
      successMissingSession: "支付返回链接缺少支付会话信息。",
      cancelTitle: "支付已取消",
      cancelDescription: "该转诊订单仍处于待支付状态，稍后可继续支付。",
      viewOrder: "查看转诊订单",
      retryPayment: "重新支付",
      continuePayment: "继续支付",
      paymentReturnedError: "暂时无法确认支付结果。",
      mockTitle: "演示支付页",
      mockDescription:
        "当前已启用转诊演示支付模式。你可以使用下面的操作来模拟支付结果。",
      mockOrderLabel: "转诊订单",
      mockSuccess: "模拟支付成功",
      mockCancel: "模拟取消支付",
      mockDisabled:
        "当前未启用转诊演示支付模式。请在开发环境下开启 VITE_REFERRAL_MOCK_CHECKOUT=1 后再使用此页面。",
    },
    orderDetail: {
      title: "转诊订单",
      latestUpdate: "最新进展",
      latestUpdateTime: "更新时间",
      latestUpdateFallback: "转诊请求正在处理中，我们会持续更新此页面。",
      pendingPaymentNotice:
        "请先完成支付，我们将在支付后开始人工协调预约流程。",
      consultationConfirmedNotice:
        "问诊时间已确认，请按下方显示时间准时参加；如时间有变动，我们会及时通知你。",
      consultationTime: "问诊时间",
      fulfillmentDeadline: "取得可安排反馈的截止时间",
      consultationProvider: "医生或服务方",
      consultationPlatform: "面诊平台",
      consultationTimeZone: "时区",
      consultationJoinLink: "加入面诊",
      consultationInstructions: "操作说明",
      refundStatus: "退款状态",
      timeline: "状态时间线",
      noTimeline: "暂无状态更新。",
      assignedAgent: "负责专员",
      serviceFee: "服务费",
      triageSummary: "病例摘要快照",
      recommendationReason: "推荐原因",
      manualFulfillmentNotice:
        "该订单当前由平台人工协调推进，团队正在继续联系医院或医生安排后续流程。",
      selectedHospital: "医院",
      selectedContact: "内部处理",
      agreementVersion: "协议版本",
      orderId: "订单号",
      loadFailed: "加载转诊订单详情失败。",
      systemProgress: {
        paymentReceived: "已收到支付，订单正在等待平台内部接单处理。",
        consultationTimeConfirmed: "问诊时间已确认。",
        refundReviewInProgress: "当前正在处理你的退款审核，请留意后续通知。",
        refundReviewInitiated: "已发起退款审核。",
        refundCompleted: "退款已完成。",
      },
    },
    dashboard: {
      title: "转诊订单",
      empty: "暂无转诊订单。",
      viewOrder: "查看订单",
      consultationTime: "问诊时间",
      latestStatus: "最新状态",
    },
    admin: {
      title: "转诊运营台",
      description: "管理已支付转诊订单、内部处理进度与退款结果。",
      workspaceTabs: {
        workbench: "订单跟进工作台",
        catalog: "医院与目录维护（Admin）",
        catalogPermission: "仅管理员",
      },
      detailTabs: {
        operations: "推进与操作",
        patient: "患者分诊信息",
        refund: "退款管理",
        timeline: "时间线与日志",
      },
      filtersTitle: "订单筛选",
      statusFilter: "状态",
      statusAll: "全部状态",
      assignedToMe: "仅看分配给我",
      sortDirection: "排序方向",
      sortNewest: "最新优先",
      sortOldest: "最早优先",
      refresh: "刷新订单",
      orderListTitle: "转诊订单列表",
      orderDetailTitle: "转诊订单详情",
      noOrders: "暂无转诊订单。",
      urgencyMinutes: "已等待 {{minutes}} 分钟",
      unassigned: "未分配",
      contactPending: "待分配联系人",
      manualFulfillmentBadge: "人工协调",
      manualFulfillmentDetail:
        "该订单来自分诊排序结果，当前仍需人工外联或后续补全本地映射。",
      noLocalHospitalMapping:
        "该订单目前还没有本地医院映射，当前请继续按人工外联方式处理；如有需要可后续再补录本地目录。",
      recommendationReason: "推荐原因",
      patient: "患者",
      triageSummary: "患者摘要",
      timeline: "时间线",
      operations: "操作记录",
      notificationFailures: "通知发送异常",
      noNotificationFailures: "暂无终止重试的通知异常。",
      claimOrder: "认领订单",
      assignOrder: "分配订单",
      assignPlaceholder: "选择处理人",
      assignContactTitle: "分配联系人",
      assignContact: "保存联系人",
      assignContactPlaceholder: "选择医院联系人",
      noContactsForHospital:
        "该医院暂未配置可用联系人，当前请继续按人工方式跟进订单。",
      updateStatus: "更新状态",
      reason: "原因",
      note: "备注",
      addNote: "添加备注",
      patientProgressTitle: "患者可见进展更新",
      patientProgressPlaceholder: "填写会展示在患者转诊订单页上的进展说明。",
      publishPatientProgress: "发布进展更新",
      contactAttemptTitle: "联系结果",
      bookingResultTitle: "挂号进展",
      consultationTimeTitle: "问诊时间",
      beginTimeCoordination: "开始协调面诊时间",
      refundTitle: "退款处理",
      actionOutcome: "结果",
      actionSuccess: "已保存",
      consultationTimeInput: "确认问诊时间",
      consultationTimeZone: "IANA 时区，例如 Asia/Shanghai",
      consultationProviderName: "医生或服务方",
      consultationPlatform: "线上面诊平台",
      consultationJoinUrl: "HTTPS 加入链接",
      consultationInstructions: "患者操作说明",
      consultationTimeNote: "排期备注",
      initiateRefund: "发起退款",
      approveRefund: "批准退款",
      rejectRefund: "驳回退款",
      refundReasonCode: "退款原因",
      refundReasonDetail: "退款说明",
      refundReviewNote: "审核备注",
      noSelection: "请选择一笔订单查看详情。",
      loadFailed: "加载转诊后台数据失败。",
      paymentStatus: "支付状态",
      listSummary: "左侧盯住待处理队列，右侧只展开当前订单的操作面板。",
      detailSummary:
        "把推进动作、患者信息、退款和日志拆开后，长工单也能稳定处理。",
      prevPage: "上一页",
      nextPage: "下一页",
      refundReasonCodes: {
        contact_failed: "联系人对接失败",
        booking_failed: "挂号失败",
        sla_expired: "超过两个工作日反馈时限",
        patient_requested: "患者申请",
        internal_exception: "内部异常",
      },
      contactOutcomes: {
        connected: "已联系上",
        no_response: "暂无回复",
        failed: "联系失败",
      },
      bookingOutcomes: {
        progressing: "处理中",
        failed: "失败",
        scheduled: "已排期",
      },
      catalog: {
        title: "医院与联系人目录",
        description: "维护 MVP 流程可用的医院与转诊联系人。",
        hospitals: "医院",
        contacts: "联系人",
        department: "科室",
        createHospital: "新建医院",
        editHospital: "编辑医院",
        createContact: "新建联系人",
        editContact: "编辑联系人",
        nameZh: "名称（中文）",
        nameEn: "名称（英文）",
        cityZh: "城市（中文）",
        cityEn: "城市（英文）",
        contactName: "联系人姓名",
        roleType: "角色 / 头衔",
        languages: "支持语言",
        specialtyTags: "专长标签",
        avgResponseTime: "平均响应时长（分钟）",
        successRate: "成功率（%）",
        internalNotes: "内部备注",
        selectedHospital: "所属医院",
        activeState: "启用状态",
        saveHospital: "保存医院",
        saveContact: "保存联系人",
        emptyHospitals: "暂无医院数据。",
        emptyContacts: "暂无转诊联系人。",
      },
    },
  },
} as const;

export function getReferralCopy(lang: ReferralLang) {
  return referralCopyByLang[lang];
}
