import type { DoctorSpecialtyTag } from "./taxonomy";

export type SpecialtyIntent = {
  id: string;
  triggerKeywords: string[];
  departmentTerms: string[];
  normalizedTags: DoctorSpecialtyTag[];
};

export const SPECIALTY_INTENTS: SpecialtyIntent[] = [
  {
    id: "musculoskeletal",
    triggerKeywords: [
      "膝",
      "膝盖",
      "膝关节",
      "关节",
      "积液",
      "积水",
      "骨",
      "骨头",
      "肌肉",
      "韧带",
      "半月板",
      "运动损伤",
      "arthritis",
      "joint",
      "knee",
      "orthopedic",
      "orthopaedic",
      "ligament",
      "meniscus",
      "rheumat",
      "swelling",
    ],
    departmentTerms: [
      "骨科",
      "关节",
      "运动医学",
      "创伤",
      "风湿",
      "骨外",
      "orthop",
      "sports medicine",
      "rheumat",
      "joint",
    ],
    normalizedTags: [
      "musculoskeletal",
      "trauma_fracture",
      "rheumatology",
      "sports_medicine",
    ],
  },
  {
    id: "trauma_fracture",
    triggerKeywords: [
      "骨折",
      "创伤",
      "外伤",
      "摔伤",
      "跌倒",
      "面部骨折",
      "胫骨",
      "腓骨",
      "fracture",
      "trauma",
      "injury",
      "fall",
      "fell",
      "tibia",
      "fibula",
    ],
    departmentTerms: [
      "骨科",
      "创伤",
      "急诊",
      "orthop",
      "fracture",
      "trauma",
      "emergency",
    ],
    normalizedTags: ["trauma_fracture", "musculoskeletal"],
  },
  {
    id: "oral_maxillofacial",
    triggerKeywords: [
      "颌面",
      "口腔颌面",
      "上颌",
      "下颌",
      "面部骨折",
      "面骨",
      "jaw",
      "maxillofacial",
      "oral surgery",
      "facial fracture",
      "mandible",
      "maxilla",
    ],
    departmentTerms: [
      "口腔",
      "颌面",
      "口腔外科",
      "oral",
      "maxillofacial",
      "dental",
      "oral surgery",
    ],
    normalizedTags: ["oral_maxillofacial"],
  },
  {
    id: "neurology",
    triggerKeywords: [
      "头痛",
      "偏头痛",
      "头晕",
      "麻木",
      "抽搐",
      "癫痫",
      "中风",
      "神经",
      "migraine",
      "headache",
      "dizziness",
      "numbness",
      "seizure",
      "stroke",
      "neurolog",
    ],
    departmentTerms: ["神经内科", "神经科", "脑", "neurolog"],
    normalizedTags: ["neurology"],
  },
  {
    id: "digestive",
    triggerKeywords: [
      "胃",
      "腹痛",
      "肚子",
      "腹泻",
      "便秘",
      "恶心",
      "呕吐",
      "反酸",
      "烧心",
      "stomach",
      "abdomen",
      "abdominal",
      "diarrhea",
      "constipation",
      "vomit",
      "gastric",
      "gastro",
    ],
    departmentTerms: ["消化", "胃肠", "gastro", "digestive"],
    normalizedTags: ["digestive"],
  },
  {
    id: "respiratory",
    triggerKeywords: [
      "咳嗽",
      "咳痰",
      "气短",
      "呼吸困难",
      "肺",
      "哮喘",
      "cough",
      "phlegm",
      "wheeze",
      "asthma",
      "dyspnea",
      "shortness of breath",
      "respirat",
      "pulmon",
    ],
    departmentTerms: ["呼吸", "肺", "respirat", "pulmon"],
    normalizedTags: ["respiratory"],
  },
  {
    id: "cardiology",
    triggerKeywords: [
      "胸痛",
      "心悸",
      "胸闷",
      "高血压",
      "心脏",
      "heart",
      "cardio",
      "palpitation",
      "hypertension",
      "chest pain",
    ],
    departmentTerms: ["心内", "心血管", "cardio", "heart"],
    normalizedTags: ["cardiology"],
  },
  {
    id: "gynecology",
    triggerKeywords: [
      "月经",
      "痛经",
      "阴道",
      "妇科",
      "卵巢",
      "子宫",
      "pregnancy",
      "menstrual",
      "gyne",
      "uterus",
      "ovary",
    ],
    departmentTerms: ["妇科", "产科", "gyne", "obstet"],
    normalizedTags: ["gynecology"],
  },
  {
    id: "pediatrics",
    triggerKeywords: [
      "儿童",
      "小孩",
      "宝宝",
      "儿科",
      "婴儿",
      "child",
      "children",
      "infant",
      "pediatric",
    ],
    departmentTerms: ["儿科", "儿童", "pediatric"],
    normalizedTags: ["pediatrics"],
  },
  {
    id: "dermatology",
    triggerKeywords: [
      "皮肤",
      "皮疹",
      "湿疹",
      "瘙痒",
      "痘",
      "rash",
      "itch",
      "eczema",
      "dermat",
    ],
    departmentTerms: ["皮肤", "dermat"],
    normalizedTags: ["dermatology"],
  },
];

export const GENERAL_DEPARTMENT_TERMS = [
  "全科",
  "综合",
  "内科",
  "急诊",
  "general",
  "family medicine",
  "internal medicine",
  "emergency",
];
