type Lang = "en" | "zh";

const visitCopyByLang = {
  en: {
    invalidToken: "Missing or invalid token.",
    appointmentNotFound: "Appointment not found.",
    noMessages: "No messages yet. Start your consultation below.",
    sendFailed: "Failed to send message. Please retry.",
    composerPlaceholder: "Type your message and describe your concern...",
    composerHint: "Enter to send, Shift+Enter for new line",
    composerReadOnlyHint: "Read-only ({{status}})",
    historyRetentionNote: "聊天记录保留 7 天",
    intakeTitle: "Pre-visit Intake",
    intakeEmpty: "No structured intake provided.",
    intakeChiefComplaint: "Chief complaint",
    intakeDuration: "Duration",
    intakeMedicalHistory: "Medical history",
    intakeMedications: "Current medications",
    intakeAllergies: "Allergies",
    intakeAgeGroup: "Age group",
    intakeOtherSymptoms: "Other symptoms",
    assignedDoctorFallback: "Assigned doctor",
    departmentFallback: "Department",
    unknownPatient: "Unknown patient",
    appointmentTypeOnline: "Online chat",
    appointmentTypeVideo: "Video call",
    appointmentTypeInPerson: "In person",
    tbd: "TBD",
    chatEnabled: "Chat enabled",
    readOnly: "Read only",
    reconnecting: "Reconnecting...",
    doctorTimeChina: "Doctor time (China)",
    roomStatus: "Room status",
    consultationEndedSuccess: "Consultation ended. Room is now read-only.",
    consultationEndFailed: "Failed to end consultation.",
    endConsultation: "End Consultation",
    endConsultationTitle: "End Consultation?",
    endConsultationDesc:
      "Are you sure you want to end this consultation? The patient will no longer be able to send messages, and the chat will become read-only.",
    cancel: "Cancel",
    ending: "Ending...",
    confirmEnd: "Confirm End",
    aiTriageSummaryTitle: "AI Triage Summary",
    aiTriageSummaryEmpty: "No triage summary available.",
    patientContextTitle: "Patient Context",
    preVisitIntakeTitle: "Pre-visit Intake",
    loadEarlierMessages: "Load earlier messages",
    loadingEarlierMessages: "Loading earlier messages...",
    loading: "Loading...",
  },
  zh: {
    invalidToken: "链接无效或已缺失。",
    appointmentNotFound: "未找到会诊预约。",
    noMessages: "暂无消息，请在下方开始会诊。",
    sendFailed: "发送失败，请重试。",
    composerPlaceholder: "输入消息，描述你的问题...",
    composerHint: "Enter 发送，Shift+Enter 换行",
    composerReadOnlyHint: "只读（{{status}}）",
    historyRetentionNote: "聊天记录保留 7 天",
    intakeTitle: "诊前结构化信息",
    intakeEmpty: "暂无结构化诊前信息。",
    intakeChiefComplaint: "主诉",
    intakeDuration: "病程/持续时间",
    intakeMedicalHistory: "既往史",
    intakeMedications: "当前用药",
    intakeAllergies: "过敏史",
    intakeAgeGroup: "年龄段",
    intakeOtherSymptoms: "其他症状",
    assignedDoctorFallback: "已分配医生",
    departmentFallback: "科室",
    unknownPatient: "未知患者",
    appointmentTypeOnline: "图文会诊",
    appointmentTypeVideo: "视频会诊",
    appointmentTypeInPerson: "线下面诊",
    tbd: "待定",
    chatEnabled: "可聊天",
    readOnly: "只读",
    reconnecting: "重连中...",
    doctorTimeChina: "医生时间（中国）",
    roomStatus: "房间状态",
    consultationEndedSuccess: "会诊已结束，房间已切换为只读。",
    consultationEndFailed: "结束会诊失败。",
    endConsultation: "结束会诊",
    endConsultationTitle: "确认结束会诊？",
    endConsultationDesc:
      "确认结束后，患者将无法继续发送消息，聊天室会变为只读。",
    cancel: "取消",
    ending: "结束中...",
    confirmEnd: "确认结束",
    aiTriageSummaryTitle: "AI 分诊摘要",
    aiTriageSummaryEmpty: "暂无分诊摘要。",
    patientContextTitle: "患者背景",
    preVisitIntakeTitle: "诊前信息",
    loadEarlierMessages: "加载更早消息",
    loadingEarlierMessages: "正在加载更早消息...",
    loading: "加载中...",
  },
} as const;

export function getVisitCopy(lang: Lang) {
  return visitCopyByLang[lang];
}
