type Lang = "en" | "zh";

const visitCopyByLang = {
  en: {
    invalidToken: "Missing or invalid token.",
    appointmentNotFound: "Appointment not found.",
    noMessages: "No messages yet. Start your consultation below.",
    sendFailed: "Failed to send message. Please retry.",
    composerPlaceholder: "Type your message and describe your concern...",
    composerHint: "Enter to send, Shift+Enter for new line",
    composerReadOnlyHint: "Consultation ended. Chat is read-only.",
    historyRetentionNote: "聊天记录保留 7 天",
    intakeTitle: "Pre-visit Intake",
    intakeEmpty: "No structured intake provided.",
    intakeChiefComplaint: "Chief complaint",
    intakeDuration: "Duration",
    intakeMedicalHistory: "Medical history",
    intakeMedications: "Current medications",
    intakeAllergies: "Allergies",
    intakeAgeGroup: "Age group",
    intakeOtherSymptoms: "Other symptoms",
    assignedDoctorFallback: "Assigned doctor",
    departmentFallback: "Department",
    unknownPatient: "Unknown patient",
    appointmentTypeOnline: "Online chat",
    appointmentTypeVideo: "Video call",
    appointmentTypeInPerson: "In person",
    tbd: "TBD",
    chatEnabled: "Chat enabled",
    readOnly: "Read only",
    reconnecting: "Reconnecting...",
    doctorTimeChina: "Doctor time (China)",
    backToAppointments: "Back to Appointments",
    roomStatus: "Room status",
    timerAriaLabel: "Consultation time remaining {{time}}",
    fiveMinWarningBanner:
      "⚠️ Less than 5 minutes remaining. Please prepare to summarize the consultation.",
    timeExceededTitle: "Consultation Time Exceeded",
    timeExceededDesc:
      "The base consultation time has ended. You can end the visit to draft the summary now, or extend 5 minutes for free to complete your medical advice.",
    timeExceededDescNoExtension:
      "The consultation time has ended and the free extension has been used. Please end the visit and draft the summary.",
    extendFiveMins: "Extend 5 Mins",
    extendingTimer: "Extending...",
    endVisitDraftSummary: "End Visit & Draft Summary",
    timerExtendAlreadyUsed: "This consultation has already used the free 5-minute extension.",
    timerExtendFailed: "Failed to extend consultation time. Please retry.",
    consultationEndedSuccess: "Medical summary signed. Room is now read-only.",
    consultationEndFailed: "Failed to end consultation.",
    endConsultation: "End Visit",
    generateSummaryNow: "Generate Summary",
    endConsultationTitle: "End Visit & Generate Record",
    endConsultationDesc:
      "The consultation will be closed to new messages. Our AI will automatically generate a medical summary based on this conversation for your review.",
    cancel: "Cancel",
    ending: "Ending...",
    confirmEnd: "Generate Summary",
    reviewMedicalSummaryTitle: "Review Medical Summary",
    medicalSummaryAIDisclaimer:
      "Drafted by AI based on the consultation history. Please review and edit before signing.",
    medicalSummaryChiefComplaint: "Chief Complaint",
    medicalSummaryHpi: "History of Present Illness",
    medicalSummaryPmh: "Past Medical History",
    medicalSummaryAssessment: "Assessment / Diagnosis",
    medicalSummaryPlan: "Plan / Recommendations",
    medicalSummaryCancel: "Cancel",
    medicalSummaryRegenerate: "Regenerate AI Draft",
    medicalSummarySign: "Sign & Send to Patient",
    medicalSummaryGenerating: "Generating AI draft...",
    medicalSummaryGeneratingWithCountdown: "Generating AI draft... ({{time}} left)",
    medicalSummarySigning: "Signing & sending...",
    medicalSummaryDraftFailed: "Failed to generate medical summary draft.",
    medicalSummaryDraftTimeout:
      "AI draft was not generated within 2 minutes. Please complete manually and sign.",
    medicalSummaryDraftTimeoutHint:
      "You can continue writing this summary manually and sign/send to the patient.",
    medicalSummaryRequiredFields: "Please complete all required sections before signing.",
    medicalSummarySignFailed: "Failed to sign medical summary.",
    aiTriageSummaryTitle: "AI Triage Summary",
    aiTriageSummaryEmpty: "No triage summary available.",
    patientContextTitle: "Patient Context",
    preVisitIntakeTitle: "Pre-visit Intake",
    loadEarlierMessages: "Load earlier messages",
    loadingEarlierMessages: "Loading earlier messages...",
    loading: "Loading...",
  },
  zh: {
    invalidToken: "链接无效或已缺失。",
    appointmentNotFound: "未找到会诊预约。",
    noMessages: "暂无消息，请在下方开始会诊。",
    sendFailed: "发送失败，请重试。",
    composerPlaceholder: "输入消息，描述你的问题...",
    composerHint: "Enter 发送，Shift+Enter 换行",
    composerReadOnlyHint: "会诊已结束，当前为只读模式。",
    historyRetentionNote: "聊天记录保留 7 天",
    intakeTitle: "诊前结构化信息",
    intakeEmpty: "暂无结构化诊前信息。",
    intakeChiefComplaint: "主诉",
    intakeDuration: "病程/持续时间",
    intakeMedicalHistory: "既往史",
    intakeMedications: "当前用药",
    intakeAllergies: "过敏史",
    intakeAgeGroup: "年龄段",
    intakeOtherSymptoms: "其他症状",
    assignedDoctorFallback: "已分配医生",
    departmentFallback: "科室",
    unknownPatient: "未知患者",
    appointmentTypeOnline: "图文会诊",
    appointmentTypeVideo: "视频会诊",
    appointmentTypeInPerson: "线下面诊",
    tbd: "待定",
    chatEnabled: "可聊天",
    readOnly: "只读",
    reconnecting: "重连中...",
    doctorTimeChina: "医生时间（中国）",
    backToAppointments: "返回预约列表",
    roomStatus: "房间状态",
    timerAriaLabel: "会诊剩余时间 {{time}}",
    fiveMinWarningBanner:
      "⚠️ 本次问诊还有不到 5 分钟结束，请医生准备总结病情。",
    timeExceededTitle: "问诊时间已到",
    timeExceededDesc:
      "基础问诊时间已用尽。您可以直接结束并生成病历，或者为了完善医嘱免费延长 5 分钟。",
    timeExceededDescNoExtension: "基础问诊时间已用尽，且已使用过免费延长时长。请直接结束会诊并生成病历。",
    extendFiveMins: "免费延长 5 分钟",
    extendingTimer: "延长中...",
    endVisitDraftSummary: "结束会诊并生成病历",
    timerExtendAlreadyUsed: "本次会诊已使用过免费延长 5 分钟。",
    timerExtendFailed: "延长会诊时间失败，请重试。",
    consultationEndedSuccess: "病历已签发，房间已切换为只读。",
    consultationEndFailed: "结束会诊失败。",
    endConsultation: "结束会诊",
    generateSummaryNow: "生成总结",
    endConsultationTitle: "结束会诊并生成病历摘要",
    endConsultationDesc:
      "会诊结束后，将不再接收新消息。我们的 AI 会基于本次对话自动生成医疗摘要，供您审核。",
    cancel: "取消",
    ending: "结束中...",
    confirmEnd: "生成摘要",
    reviewMedicalSummaryTitle: "审核诊疗小结",
    medicalSummaryAIDisclaimer: "该草稿由 AI 基于问诊记录生成，请在签发前审核并编辑。",
    medicalSummaryChiefComplaint: "主诉",
    medicalSummaryHpi: "现病史",
    medicalSummaryPmh: "既往史",
    medicalSummaryAssessment: "初步诊断",
    medicalSummaryPlan: "处置与建议",
    medicalSummaryCancel: "取消",
    medicalSummaryRegenerate: "重新生成 AI 草稿",
    medicalSummarySign: "签发并发送给患者",
    medicalSummaryGenerating: "正在生成 AI 草稿...",
    medicalSummaryGeneratingWithCountdown: "正在生成 AI 草稿...（剩余 {{time}}）",
    medicalSummarySigning: "签发中...",
    medicalSummaryDraftFailed: "生成病历草稿失败。",
    medicalSummaryDraftTimeout: "2 分钟内未成功生成 AI 草稿。请手动补充后签发。",
    medicalSummaryDraftTimeoutHint: "你可以继续手动填写该小结，然后签发并发送给患者。",
    medicalSummaryRequiredFields: "请先完整填写所有必填内容后再签发。",
    medicalSummarySignFailed: "签发病历失败。",
    aiTriageSummaryTitle: "AI 分诊摘要",
    aiTriageSummaryEmpty: "暂无分诊摘要。",
    patientContextTitle: "患者背景",
    preVisitIntakeTitle: "诊前信息",
    loadEarlierMessages: "加载更早消息",
    loadingEarlierMessages: "正在加载更早消息...",
    loading: "加载中...",
  },
} as const;

export function getVisitCopy(lang: Lang) {
  return visitCopyByLang[lang];
}
