export type HospitalsLang = "en" | "zh";

const hospitalsCopyByLang = {
  en: {
    pageHeader: {
      subtitle: "Browse Hospitals & Doctors",
      backToHome: "Back to Home",
    },
    browser: {
      breadcrumbHospitals: "Hospitals",
      breadcrumbDepartmentsFallback: "Departments",
      breadcrumbDoctorsFallback: "Doctors",
      selectHospitalTitle: "Select a Hospital",
      selectHospitalIntro:
        "Quickly find top medical institutions by name, tier, or city.",
      selectHospitalDescription: (count: number) =>
        `Choose from ${count} premier hospitals in Shanghai`,
      selectDepartmentTitle: "Select a Department",
      doctorsTitle: "Doctors",
      doctorsCountLabel: (count: number) => `${count} specialists available`,
      back: "Back",
      backToDepartments: "Back to Departments",
      searchHospitalsLabel: "Search hospitals",
      searchHospitalsPlaceholder: "Search hospitals...",
      searchDoctorsLabel: "Search doctors",
      cityLabel: "City",
      allCities: "All cities",
      noHospitalsFound: "No hospitals found.",
      noDepartmentsFound: "No departments found.",
      backToHospitals: "Back to Hospitals",
      departmentHeroSubtitle:
        "Please select a specialized department for your consultation.",
      hospitalProfileDescription:
        "A nationally recognized tertiary hospital with strong comprehensive care and specialized expertise. We provide world-class medical services to international and local patients.",
      enterDepartment: "Enter department",
      departmentCardSubtitle: "Specialized consultation and treatment",
      hospitalCardDescription:
        "A nationally recognized tertiary hospital with strong comprehensive care and specialist services in oral and maxillofacial medicine.",
      viewDoctors: "View Doctors",
      searchPlaceholder: "Search by name or expertise...",
      noDoctorsFound: "No doctors found",
      specialtyLabel: "Specialty: ",
      expertiseLabel: "Expertise: ",
      viewProfile: "View Profile",
    },
    doctorDetail: {
      subtitle: "AI-Powered Medical Bridge to China",
      back: "Back",
      backToHome: "Back to Home",
      notFound: "Doctor not found",
      pageTitle: "Doctor Detail",
      bookAppointment: "Book Appointment",
      consultationService: "Consultation Service",
      consultationDuration: "30 minutes",
      expertise: "Expertise",
      ratings: "Ratings",
      hospitalInformation: "Hospital Information",
      securePaymentGuarantee: "Secure payment • AI-powered matching",
      hospitalWebsite: "Hospital Website",
      viewOnHaodf: "View on Haodf",
      defaultDoctorName: "Doctor",
      satisfactionLabel: "Satisfaction",
      attitudeLabel: "Attitude",
      recommendationLabel: "Recommendation",
      backNavigation: "Back",
      bookingPanelAria: "Consultation booking panel",
      heroProfileAria: "Doctor profile",
      noDataYet: "No details available yet",
      noStatistics: "No statistics yet",
    },
  },
  zh: {
    pageHeader: {
      subtitle: "浏览医院与医生",
      backToHome: "返回首页",
    },
    browser: {
      breadcrumbHospitals: "医院",
      breadcrumbDepartmentsFallback: "科室",
      breadcrumbDoctorsFallback: "医生",
      selectHospitalTitle: "选择合作医院",
      selectHospitalIntro: "支持搜索医院名称、等级与城市，快速找到顶尖医疗机构。",
      selectHospitalDescription: (count: number) =>
        `可从上海 ${count} 家重点医院中选择`,
      selectDepartmentTitle: "选择科室",
      doctorsTitle: "医生列表",
      doctorsCountLabel: (count: number) => `${count} 位专家可咨询`,
      back: "返回",
      backToDepartments: "返回科室",
      searchHospitalsLabel: "搜索医院",
      searchHospitalsPlaceholder: "搜索医院...",
      searchDoctorsLabel: "搜索医生",
      cityLabel: "城市",
      allCities: "全部城市",
      noHospitalsFound: "未找到医院。",
      noDepartmentsFound: "未找到科室。",
      backToHospitals: "返回医院列表",
      departmentHeroSubtitle: "请选择用于本次咨询的专业科室。",
      hospitalProfileDescription:
        "这是一所全国知名的三甲医院，具备完善的综合医疗体系与专业科室布局，为国际和本地患者提供高质量的诊疗与连续性随访服务。",
      enterDepartment: "进入科室",
      departmentCardSubtitle: "精准专科会诊与治疗服务",
      hospitalCardDescription:
        "全国知名的综合性三甲医院，特色科室包含整形外科、口腔科、骨科等，具备完整的检查与术后随访体系。",
      viewDoctors: "查看医生",
      searchPlaceholder: "按姓名或擅长方向搜索...",
      noDoctorsFound: "未找到医生",
      specialtyLabel: "专科：",
      expertiseLabel: "擅长：",
      viewProfile: "查看详情",
    },
    doctorDetail: {
      subtitle: "AI 驱动的中外医疗桥梁",
      back: "返回",
      backToHome: "返回首页",
      notFound: "未找到医生",
      pageTitle: "医生详情",
      bookAppointment: "预约咨询",
      consultationService: "咨询服务",
      consultationDuration: "30分钟",
      expertise: "擅长领域",
      ratings: "评分",
      hospitalInformation: "医院信息",
      securePaymentGuarantee: "安全支付 • AI 智能匹配",
      hospitalWebsite: "医院官网",
      viewOnHaodf: "查看好大夫",
      defaultDoctorName: "医生",
      satisfactionLabel: "满意度",
      attitudeLabel: "态度",
      recommendationLabel: "推荐度",
      backNavigation: "返回",
      bookingPanelAria: "预约服务区域",
      heroProfileAria: "医生信息区域",
      noDataYet: "暂无详细介绍",
      noStatistics: "暂无统计",
    },
  },
} as const;

export function getHospitalsCopy(lang: HospitalsLang) {
  return hospitalsCopyByLang[lang];
}
