export const referralCopyEn = {
  navigation: {
    backToTriage: "Back to Triage",
    backToSelection: "Back to Contact Selection",
    backToConfirmation: "Back to Confirmation",
    backToOrders: "Back to My Orders",
    backToDashboard: "Back to Dashboard",
    backToOrder: "Back to Order",
  },
  statusLabels: {
    pending_payment: "Pending payment",
    paid_pending_assignment: "Paid, waiting for assignment",
    assigned: "Assigned",
    contacting: "Contacting channel",
    booking_in_progress: "Booking in progress",
    time_coordination: "Coordinating consultation time",
    scheduled: "Consultation scheduled",
    completed: "Completed",
    refund_pending_review: "Refund under review",
    refund_processing: "Refund processing",
    refunded: "Refunded",
    cancelled: "Cancelled",
  },
  refundStatusLabels: {
    pending_review: "Pending review",
    approved: "Approved",
    processing: "Processing",
    refunded: "Refunded",
    rejected: "Rejected",
  },
  operationLabels: {
    patient_notification: "Progress update shared with you",
    consultation_time_confirmed: "Consultation time confirmed",
    consultation_time_updated: "Consultation time updated",
    refund_requested: "Refund requested",
    refund_completed: "Refund completed",
  },
  common: {
    loading: "Loading referral details...",
    unknown: "Unknown",
    notAvailable: "Not available",
    contactPending: "MediBridge Coordination Team",
    refresh: "Refresh",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    active: "Active",
    inactive: "Inactive",
    none: "None",
  },
  selection: {
    eyebrow: "Referral MVP",
    title: "Select a MediBridge Platform Coordinator",
    description:
      "Choose the MediBridge platform coordinator who will help contact the selected hospital and arrange the next steps.",
    recommendedDepartment: "Recommended department",
    noContacts:
      "No individual coordinator is currently available for this hospital.",
    teamName: "MediBridge Coordination Team",
    teamDescription:
      "The MediBridge platform team will assign an appropriate coordinator after payment. This team is not an official hospital department.",
    coordinatorRole: "MediBridge platform coordinator",
    contactLanguages: "Languages",
    contactSpecialties: "Tags",
    responseTime: "Avg. response",
    successRate: "Success rate",
    chooseContact: "Choose this coordinator",
    chooseTeam: "Choose the coordination team",
    triageSummary: "Triage summary",
    loadFailed: "Failed to load referral contact options.",
  },
  confirmation: {
    title: "Confirm Referral Service",
    description: "Review the service scope before creating the referral order.",
    hospital: "Selected hospital",
    contact: "MediBridge platform coordinator",
    fulfillmentDescription:
      "After payment, the selected MediBridge platform coordinator will contact the hospital and continue the registration and scheduling process.",
    serviceDescription:
      "The ¥199 fee covers MediBridge coordination only: contacting the selected hospital, assisting with registration, and coordinating an online consultation time. Hospital registration, physician consultation, and other third-party fees are not included.",
    priceLabel: "Service fee",
    refundPolicyTitle: "Refund policy",
    refundPolicy:
      "The ¥199 service fee will be fully refunded to the original payment method if contact or registration clearly fails, or if no schedulable response is received within two business days after payment.",
    disclaimerTitle: "Disclaimer",
    disclaimer:
      "MediBridge provides coordination support and does not guarantee registration, diagnosis, treatment, or medical outcomes. The selected coordinator is a MediBridge platform representative, not hospital staff.",
    manualHandlingNotice:
      "After your order is placed, we will manually coordinate with the hospital or doctor based on the triage recommendation.",
    agreementLabel:
      "I understand the service scope, refund rule, and disclaimer, and I agree to proceed.",
    continueToPayment: "Continue to Payment",
    agreementRequired: "Please accept the agreement before continuing.",
    invalidContact:
      "The selected coordinator is no longer available for this hospital. Please return and choose again.",
    loadFailed: "Failed to load referral confirmation details.",
  },
  payment: {
    title: "Pay Service Fee",
    description:
      "Complete payment to create a paid referral order for internal broker handling.",
    payNow: "Pay now",
    processing: "Processing...",
    alreadyPaid: "This referral order is already paid.",
    paymentFailed: "Payment could not be completed. Please try again.",
    paymentWaiting: "Preparing payment session...",
    missingOrder: "Referral order is missing or unavailable.",
    selectedHospital: "Hospital",
    selectedContact: "Internal handling",
    currentStatus: "Current status",
    serviceFee: "Service fee",
    payHelp:
      "After payment, the order will move into internal handling and assignment.",
    successTitle: "Payment confirmed",
    successDescription:
      "Your referral order has been created and sent for internal assignment.",
    successMissingSession: "Payment session is missing from the return URL.",
    cancelTitle: "Payment cancelled",
    cancelDescription:
      "The referral order is still waiting for payment. You can return and continue later.",
    viewOrder: "View referral order",
    retryPayment: "Retry payment",
    continuePayment: "Continue payment",
    paymentReturnedError: "Unable to confirm the payment result right now.",
    mockTitle: "Demo payment screen",
    mockDescription:
      "This is a simulated checkout. No external payment provider will be charged.",
    mockOrderLabel: "Referral order",
    mockSuccess: "Simulate payment success",
    mockCancel: "Simulate payment cancel",
  },
  orderDetail: {
    title: "Referral Order",
    latestUpdate: "Latest update",
    latestUpdateTime: "Updated",
    latestUpdateFallback:
      "Your referral request is in progress. We will keep this page updated.",
    pendingPaymentNotice:
      "Please complete payment first. We will start manual coordination after payment is confirmed.",
    consultationConfirmedNotice:
      "Your consultation time has been confirmed. Please attend at the scheduled time shown below. We will notify you if it changes.",
    consultationTime: "Consultation time",
    fulfillmentDeadline: "Coordination response deadline",
    consultationProvider: "Doctor or service provider",
    consultationPlatform: "Consultation platform",
    consultationTimeZone: "Time zone",
    consultationJoinLink: "Join consultation",
    consultationInstructions: "Joining instructions",
    refundStatus: "Refund status",
    timeline: "Status timeline",
    noTimeline: "No status updates yet.",
    assignedAgent: "Assigned agent",
    serviceFee: "Service fee",
    triageSummary: "Case summary snapshot",
    recommendationReason: "Recommendation reason",
    manualFulfillmentNotice:
      "This order is being handled through manual coordination. Our team is continuing to reach out to the hospital or doctor and advance the next steps.",
    selectedHospital: "Hospital",
    selectedContact: "Internal handling",
    agreementVersion: "Agreement version",
    orderId: "Order ID",
    loadFailed: "Failed to load referral order details.",
    systemProgress: {
      paymentReceived:
        "Payment received. Your referral request is now waiting for internal assignment.",
      consultationTimeConfirmed: "Consultation time confirmed.",
      refundReviewInProgress:
        "A refund review is in progress for your referral order.",
      refundReviewInitiated: "Refund review initiated.",
      refundCompleted: "Refund completed.",
    },
  },
  dashboard: {
    title: "Referral Orders",
    empty: "No referral orders yet.",
    viewOrder: "Open order",
    consultationTime: "Consultation time",
    latestStatus: "Latest status",
  },
  admin: {
    title: "Referral Operations",
    description:
      "Manage paid referral orders, internal handling progress, and refund outcomes.",
    workspaceTabs: {
      workbench: "Order tracking workspace",
      catalog: "Hospitals & catalog (Admin)",
      catalogPermission: "Admin only",
    },
    detailTabs: {
      operations: "Progress & actions",
      patient: "Patient triage info",
      refund: "Refund management",
      timeline: "Timeline & logs",
    },
    filtersTitle: "Order filters",
    statusFilter: "Status",
    statusAll: "All statuses",
    assignedToMe: "Assigned to me",
    sortDirection: "Sort direction",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    refresh: "Refresh orders",
    orderListTitle: "Referral order list",
    orderDetailTitle: "Referral order detail",
    noOrders: "No referral orders found.",
    urgencyMinutes: "Open for {{duration}}",
    unassigned: "Unassigned",
    contactPending: "Contact pending assignment",
    manualFulfillmentBadge: "Manual outreach",
    manualFulfillmentDetail:
      "This order was created from a triage-ranked hospital and still needs manual outreach or local mapping follow-up.",
    noLocalHospitalMapping:
      "This order does not have a local hospital mapping yet. Continue manual outreach, or add the hospital to the local catalog later if needed.",
    recommendationReason: "Recommendation reason",
    patient: "Patient",
    triageSummary: "Patient summary",
    timeline: "Timeline",
    operations: "Operations",
    notificationFailures: "Notification delivery failures",
    noNotificationFailures: "No terminal notification failures.",
    claimOrder: "Claim order",
    assignOrder: "Assign order",
    assignPlaceholder: "Select assignee",
    assignContactTitle: "Assign contact",
    assignContact: "Save contact",
    assignContactPlaceholder: "Select hospital contact",
    noContactsForHospital:
      "No active contacts are configured for this hospital yet. Keep the order in manual handling for now.",
    updateStatus: "Update status",
    reason: "Reason",
    note: "Note",
    addNote: "Add note",
    patientProgressTitle: "Patient-visible progress update",
    patientProgressPlaceholder:
      "Share a progress update that will appear on the patient's referral order page.",
    publishPatientProgress: "Publish progress update",
    contactAttemptTitle: "Contact attempt",
    bookingResultTitle: "Booking progress",
    consultationTimeTitle: "Consultation time",
    beginTimeCoordination: "Start time coordination",
    consultationScheduleHint:
      "Saving this arrangement moves the order to Consultation scheduled. Scheduled is not a manual status option.",
    saveAndScheduleConsultation: "Save and mark scheduled",
    saveConsultationArrangement: "Save consultation arrangement",
    consultationValidationTitle: "Complete the following items before saving:",
    consultationDraftSaved:
      "Unsaved changes are kept for this order in the current browser tab.",
    consultationValidationIssues: {
      consultation_time_required: "Select the consultation time.",
      consultation_time_invalid: "Enter a valid consultation time.",
      time_zone_required: "Enter the consultation time zone.",
      provider_required: "Enter the doctor or service provider.",
      platform_required: "Enter the consultation platform.",
      join_url_required: "Enter the joining link.",
      join_url_https_required:
        "The joining link must start with https://, for example https://www.abc.com.",
      instructions_required: "Enter the patient joining instructions.",
    },
    refundTitle: "Refund handling",
    actionOutcome: "Outcome",
    actionSuccess: "Saved",
    consultationTimeInput: "Confirmed consultation time",
    consultationTimeZone: "IANA time zone, e.g. Asia/Shanghai",
    consultationProviderName: "Doctor or service provider",
    consultationPlatform: "Consultation platform",
    consultationJoinUrl: "HTTPS joining link",
    consultationInstructions: "Patient joining instructions",
    consultationTimeNote: "Scheduling note",
    initiateRefund: "Initiate refund",
    approveRefund: "Approve refund",
    rejectRefund: "Reject refund",
    refundReasonCode: "Refund reason",
    refundReasonDetail: "Refund detail",
    refundReviewNote: "Review note",
    noSelection: "Select an order to review details.",
    loadFailed: "Failed to load referral admin data.",
    paymentStatus: "Payment status",
    listSummary:
      "Focus the queue on the left and handle the active order on the right.",
    detailSummary:
      "Keep operational controls and deep logs separated so long cases stay manageable.",
    nextStep: "Recommended next step",
    moreActions: "More actions",
    taskDescriptions: {
      await_payment:
        "Payment has not settled. Review the order and wait before starting fulfillment.",
      assign:
        "Claim the paid order or assign it to the appropriate coordinator.",
      contact:
        "Record the contact outcome. A connected result advances the order.",
      booking:
        "Record the booking result. A progressing result advances the order.",
      coordinate_time:
        "Start consultation-time coordination after booking progress is confirmed.",
      schedule:
        "Enter the confirmed provider, platform, joining link, and patient instructions.",
      complete:
        "Verify that the consultation actually occurred, then record completion. The scheduled time passing does not complete the order automatically.",
      refund_review:
        "Review the refund request and record an approval or rejection.",
      refund_processing:
        "The refund is processing. Monitor the timeline for settlement.",
      terminal:
        "This order is closed. Review the result and timeline; no fulfillment action is available.",
    },
    prevPage: "Previous",
    nextPage: "Next",
    refundReasonCodes: {
      contact_failed: "Contact failed",
      booking_failed: "Booking failed",
      sla_expired: "Two-business-day response deadline expired",
      patient_requested: "Patient requested",
      internal_exception: "Internal exception",
    },
    contactOutcomes: {
      connected: "Connected",
      no_response: "No response",
      failed: "Failed",
    },
    bookingOutcomes: {
      progressing: "Progressing",
      failed: "Failed",
      scheduled: "Scheduled",
    },
    catalog: {
      title: "Hospital & Contact Catalog",
      description:
        "Maintain the hospitals and referral contacts available to the MVP flow.",
      hospitals: "Hospitals",
      contacts: "Contacts",
      department: "Department",
      createHospital: "Create hospital",
      editHospital: "Edit hospital",
      createContact: "Create contact",
      editContact: "Edit contact",
      nameZh: "Name (ZH)",
      nameEn: "Name (EN)",
      cityZh: "City (ZH)",
      cityEn: "City (EN)",
      contactName: "Contact name",
      roleType: "Role / title",
      languages: "Languages",
      specialtyTags: "Specialty tags",
      avgResponseTime: "Avg. response time (min)",
      successRate: "Success rate (%)",
      internalNotes: "Internal notes",
      selectedHospital: "Hospital",
      activeState: "Active state",
      saveHospital: "Save hospital",
      saveContact: "Save contact",
      emptyHospitals: "No hospitals available.",
      emptyContacts: "No referral contacts available.",
    },
  },
} as const;
